# Generated by Django 3.0.3 on 2020-02-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField(choices=[(0, 'Not annotated'), (1, 'Positive sentiment'), (2, 'Negative sentiment'), (3, 'N/A because it is impossible to make out the meaning of the text (not because the sentiment is ambiguous)')], default=0)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs685.Annotator')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs685.Tweet')),
            ],
        ),
    ]
